### PR TITLE
Hardcode the toolname (ksonnet)

### LINKED ISSUE #1: It doesn't seem to be picking up the 0.8.0 release...
Thanks for putting this together! :) 

Just noticed it doesn't seem to be picking up the 0.8.0 release from github:

```
$ asdf list-all kubecfg
0.1.0....
0.2.0
0.3.0
0.4.0
0.5.0
0.6.0
0.7.0
0.7.1
0.7.2
master
```

I would try and have a look at fixing it but I'm not sure where to start in the `list-all` scrip, my bash fu isn't that strong...

### PR DESCRIPTION
**Pull request by dazoakley**
This fixes #1.

Not sure if this is the best way of going about it, but it allowed me to
install 0.8.0.

### CODE REVIEW

**Comment by adamdecaf** [comment]
Install 0.8.0 of ksonnet? 

This change looks okay to me, but I'm not super familiar with asdf. I don't know of other tools that would be installed here, so hardcoding `ksonnet` looks ok.

@nikolay Thoughts?

The CI failure is because that older Go version doesn't have `sort.Slice`. I'll remove that.

**Comment by adamdecaf** [comment]
I tried this out locally, is this the same output as you got @dazoakley? 

```
$ asdf plugin-add kubecfg  .
Cloning into '/usr/local/opt/asdf/plugins/kubecfg'...
done.

$ asdf list-all kubecfg 
0.7.0....
0.8.0
master
```

**Comment by dazoakley** [comment]
@adamdecaf yep, those are the only two tags on the https://github.com/ksonnet/ksonnet repo.  I was kind of confused where it was getting the other tags previously...

**Comment by dazoakley** [comment]
Or are we getting wires crossed as it's supposed to point at https://github.com/ksonnet/kubecfg?

**Comment by adamdecaf** [comment]
Me too...

**Comment by adamdecaf** [comment]
@dazoakley The CI seems fixed in https://github.com/Banno/asdf-ksonnet/pull/3 if you wanted to rebase that into this PR.

**Comment by nikolay** [comment]
The reason the `toolname` is not hardcoded is that the same code can be used for both [ksonnet](https://github.com/ksonnet/ksonnet) and [kubecfg](https://github.com/ksonnet/kubecfg) tools. At the time when I wrote this, `ksonnet` itself didn't have a release and we used `kubecfg`, but now the `ks` tool is available, so, I will fix the Travis configuration to test both `ks` and `kubecfg` now.

**Comment by adamdecaf** [comment]
Ah ok. Can you update the readme to show both? I think we got confused why this was referencing `kubcfg`.

**Pull request closed without merging**
